name: money_management_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.2+4

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  lottie: ^2.6.0
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  share: 2.0.4
  flutter_slidable: ^3.0.1
  http: ^1.2.1
  fluttertoast: ^8.2.5
  connectivity_plus: ^5.0.2
  get: ^4.6.6
  slider_button: ^2.1.0
  aligned_dialog: ^0.0.7
  email_validator: ^2.1.17
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/animation/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
